### DISCUSSION TITLE
Comments from gist

### DISCUSSION THREAD

**Discussion by djurny** [djurny/adaptive-lighting#1] [General]
From [jncasey](https://gist.github.com/jncasey): https://github.com/basnijholt/adaptive-lighting/discussions/506#discussioncomment-12564623

        - if:
            - condition: template
              value_template: >-
                {{
                states(adaptive_lighting|replace('adaptive_lighting','adaptive_lighting_adapt_color'))
                == 'on' }}
          then:
---
One more suggestion: filter the lights even further, to only select ones that support color_temp
```
            lights_currently_off_and_controlled_by_adaptive_lighting_entity: |-
              {{state_attr(adaptive_lighting_entity, "configuration").lights |
                expand |
                selectattr("state", "==", "off") |
                selectattr("attributes.supported_color_modes", "defined") |
                selectattr("attributes.supported_color_modes", "contains", "color_temp") |
                map(attribute="entity_id") |
                list}}
```

**Comment by djurny** [comment]
From [lnlyssg](https://gist.github.com/lnlyssg)

A small issue I had with the automation and thought it worth mentioning: check that your adaptive lighting entities are all named correctly! I had one room which I had renamed to have the room name first (i.e. switch.kitchen_adaptive_lighting_sleep_mode_adaptive instead of switch.adaptive_lighting_sleep_mode_kitchen_adaptive)

**Reply by djurny** [reply]
From [lnlyssg](https://gist.github.com/lnlyssg)

Next issue I have, a few of my older Hue lights give me UNSUPPORTED_ATTRIBUTE errors in the Z2M logs, not a major issue but any ideas how to stop the errors?

```
Error 2025-03-22 09:11:06z2m: Publish 'set' 'color_options' to 'Bedroom Hue Go' failed: 'Error: ZCL command 0x001788010116fe16/11 lightingColorCtrl.write({"options":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
```

**Reply by djurny** [reply]
Can you check in Developer tools => State for your bulb what the color_temp_options show?

This addition should have filtered that light out of the list:
```
              adaptive_lighting_light_entities: |-
                {{state_attr(adaptive_lighting_switch_entity, "configuration").lights |
                  expand |
                  selectattr("attributes.supported_color_modes", "defined") |
                  selectattr("attributes.supported_color_modes", "contains", "color_temp") |
                  selectattr("state", "==", "off") |
                  map(attribute="entity_id") |
                  list}}
```
Do you have nested light groups in home assistant where these old Hue bulbs are in? As I am not sure "how deep" expand will expand - I stopped nesting them for reasons I cannot recall myself.

Are the lights are part of a zigbee group? I think the superset of options will be used at zibgee group level.
For example, my entrance adaptive lighting lights is a single zigbee group that contains the following bulb types:

-   TRADFRI LED bulb E26/27 1100/1055/1160
    White spectrum only
-   TRADFRI bulb E26 CWS 800lm
    Color spectrum
-   TRADFRI bulb E26/E27, warm white, globe, 806 lumen
    Brightness only

In hass it shows as having supported_color_modes: color_temp, most likely as one set of the group supports it. Even though not all zigbee group members support color_temp, it will not generate any warning.

Grt,

**Reply by djurny** [reply]
From [lnlyssg](https://gist.github.com/lnlyssg)

The lights with the error are all part of my bedroom lights Zigbee group which includes 4 lights in all, it looks like  one of the four doesn’t support color_temp but the others do and they are the ones generating the error…. The three with errors are:
* https://www.zigbee2mqtt.io/devices/8718696548738.html#philips-8718696548738
* https://www.zigbee2mqtt.io/devices/7146060PH.html#philips-7146060ph
* https://www.zigbee2mqtt.io/devices/AB32840.html#osram-ab32840
* 
and the one that doesn’t support color temp but has no error is https://www.zigbee2mqtt.io/devices/7299355PH.html#philips-7299355ph

**Reply by djurny** [reply]
You can try adding `color_options` to the `filtered_attributes` in your z2m config for those bulbs giving an error, but that most likely won't work if you address the zb group. Hass cannot `expand` into zb groups...

Other options might be below:
(see gist)

As you do not necessarily need to set that `execute_if_off` every single time, this will only send it to all MQTT lights controlled by AL. You will have to (re)start hass to trigger the automation, add a different trigger or run (trigger) the automation manually (dashboard example for a different automation below):
```
          - type: tile
            entity: automation.adjust_adaptive_lighting_max_color_temp
            hide_state: true
            icon: mdi:sun-thermometer
            tap_action:
              action: perform-action
              perform_action: automation.trigger
              data:
                skip_condition: true
              target:
                entity_id: automation.adjust_adaptive_lighting_max_color_temp
```

Grt,

**Reply by djurny** [reply]
Just fiddled a little bit with my zigbee group as well. Seems that for me it's actually home assistant complaining instead of zigbee2mqtt:
```
2025-03-23 16:07:40.849 WARNING (MainThread) [homeassistant.components.mqtt.light.schema_json] Invalid color mode 'color_temp' received for entity light.entrance_family_room_ceiling_group
```

I have a `light` group for `entrance`:
```
- platform:   group
  name:       Entrance
  unique_id:  entrance_id
  entities:
    # - light.entrance_ceiling_group

    - light.entrance_family_room_ceiling_group
    # - light.bulb_ikea_e26_1100lm_no_6
    # - light.bulb_ikea_e26_1100lm_no_7
    # - light.bulb_ikea_e26_1100lm_no_8

    - light.entrance_living_room_ceiling_group
    # - light.bulb_ikea_e26_ww_800lm_no_1
    # - light.bulb_ikea_e26_ww_800lm_no_2
    # - light.bulb_ikea_e26_ww_800lm_no_3
```

Where `entrance_ceiling_group` is a zigbee group that contains all the bulbs and 
`entrance_family_room_ceiling_group` contains all the 1100lm bulbs and 
`entrance_living_room_ceiling_group` contains all WW bulbs - the ones that do not support setting `color_mode` as they cannot change color temperature.

If I use the all-encompassing zigbee group, I get those home assistant warnings that it received some attribute that it did not expect for a set of bulbs, namely the ww 800lm ones.

If I add the attribute filtering to zigbee2mqtt for just the ww 800lm bulbs and use the two seperate zigbee groups in the `light` group, both zigbee2mqtt _and_ home assistant are fine.

```
  '21':
    friendly_name: entrance_family_room_ceiling_group
    devices:
      - 0xaaa/1
      - 0xbbb/1
      - 0xccc/1
    transition: *TRANSITION_GROUP
    optimistic: *OPTIMISTIC_GROUP_IKEA
    filtered_cache: *FILTERED_CACHE_GROUP_IKEA
    filtered_attributes:
      - color_temp
```

Perhaps something you can experiment with in your setup?
Grt,
