### DISCUSSION TITLE
Use the `light` template to control adaptive lighting controlled lights instead of Ansibleized area specific scripts

### DISCUSSION THREAD

**Discussion by djurny** [djurny/adaptive-lighting#2] [Ideas]
Got some inspiration from:
- https://github.com/home-assistant/core/issues/105902#issue-2045225575 (@zolakt)
- [Setting color on a light template does not work](https://community.home-assistant.io/t/setting-color-on-a-light-template-does-not-work/331102) ([dhaupt](https://community.home-assistant.io/u/dhaupt))
- [Light template, color temperature](https://community.home-assistant.io/t/light-template-color-temperature/736888) ([ajp_anton](https://community.home-assistant.io/u/ajp_anton))

Move away from using specific scripts and generalize something like this:

```
- platform: template
  lights:
    adaptive_lighting_for_entrance:
      friendly_name: 'Adaptive lighting for entrance'
      ## state/on/off
      value_template: '{{is_state("light.entrance", "on")}}'
      turn_on:
        - action: script.auto_adaptive_lighting_for_entrance
          data:
            action: 'on'
      turn_off:
        - action: script.auto_adaptive_lighting_for_entrance
          data:
            action: 'off'
      ## brightnesss
      level_template: |-
        {%if is_state('light.entrance', 'on')%}
          {%if is_state('switch.adaptive_lighting_adapt_brightness_entrance', 'on')%}
            {{state_attr('switch.adaptive_lighting_entrance', 'brightness_pct') * 255 / 100 | round}}
          {%else%}
            {{state_attr('light.entrance', 'brightness')}}
          {%endif%}
        {%else%}
          0
        {%endif%}
      set_level:
        - action: switch.turn_off
          data:
            entity_id: switch.adaptive_lighting_adapt_brightness_entrance
        - action: light.turn_on
          data:
            brightness: '{{brightness}}'
            entity_id: light.entrance
      ## color_temp
      min_mireds_template: |-
        {{state_attr('light.entrance', 'min_mireds')}}
      max_mireds_template: |-
        {{state_attr('light.entrance', 'max_mireds')}}
      temperature_template: |-
        {%if is_state('light.entrance', 'on')%}
          {%if is_state('switch.adaptive_lighting_adapt_color_entrance', 'on')%}
            {{state_attr('switch.adaptive_lighting_entrance', 'color_temp_mired')}}
          {%else%}
            {{state_attr('light.entrance', 'color_temp')}}
          {%endif%}
        {%else%}
          0
        {%endif%}
      set_temperature:
        - action: switch.turn_off
          data:
            entity_id: switch.adaptive_lighting_adapt_color_entrance
        - action: light.turn_on
          data:
            color_temp: '{{color_temp}}'
            entity_id: light.entrance
      ## no transition
      supports_transition_template: false
```

Make some generic `script.adaptive_lighting_xxx` scripts that can do `on`/`off`/...
This seems to be an interesting way and makes dashboarding way easier.

**Comment by djurny** [comment]
Made a working `light` template that passes through most things to the first light in the adaptive lighting `lights` group.

Some things have to be in place:
- Make `light` groups containing the lights you want adaptive lighting to control.
- Name these `light` groups after the "areas" you want to lit.
- Make adaptive lighting instances that control only one `light` group (from the previous step).
- Name the adaptive lighting instances after the "areas" you want to lit.

For example:
```
- platform:   group
  name:       Entrance
  unique_id:  entrance_id
  entities:
    - light.entrance_family_room_ceiling_group
    - light.entrance_living_room_ceiling_group
```
Adaptive lighting will have three switches:
1. `switch.adaptive_lighting_entrance`
1. `switch.adaptive_lighting_adapt_brightness_entrance`
1. `switch.adaptive_lighting_adapt_color_entrance`

Now make the template for the "entrance" "area":
1. Put the following in a file called `light_templates.yaml` in a folder called `configuration.d`.
    ```
    - platform: template
      lights:
        adaptive_lighting_for_entrance:
          friendly_name: 'Adaptive lighting for entrance'
          icon_template: mdi:lightbulb-group
          value_template: '{{is_state("light.entrance", "on")}}'
          turn_on:
            - service: script.adaptive_lighting_control
              data:
                action: 'on'
                adaptive_lighting_switch_entity_id: 'switch.adaptive_lighting_entrance'
          turn_off:
            - service: script.adaptive_lighting_control
              data:
                action: 'off'
                adaptive_lighting_switch_entity_id: 'switch.adaptive_lighting_entrance'
          level_template: |-
            {%set ns=namespace()%}
            {%set ns.area_id='entrance'%}
            {%set ns.switch='switch.adaptive_lighting_'~ns.area_id%}
            {%set ns.lights=state_attr(ns.switch, "configuration").lights%}
            {{state_attr(ns.lights|first, 'brightness')}}
          set_level:
            - service: script.adaptive_lighting_control
              data:
                action: 'set_level'
                brightness: '{{brightness}}'
                adaptive_lighting_switch_entity_id: 'switch.adaptive_lighting_entrance'
          min_mireds_template: |-
            {%set ns=namespace()%}
            {%set ns.area_id='entrance'%}
            {%set ns.switch='switch.adaptive_lighting_'~ns.area_id%}
            {%set ns.lights=state_attr(ns.switch, "configuration").lights%}
            {{state_attr(ns.lights|first, 'min_mireds')}}
          max_mireds_template: |-
            {%set ns=namespace()%}
            {%set ns.area_id='entrance'%}
            {%set ns.switch='switch.adaptive_lighting_'~ns.area_id%}
            {%set ns.lights=state_attr(ns.switch, "configuration").lights%}
            {{state_attr(ns.lights|first, 'max_mireds')}}
          temperature_template: |-
            {%set ns=namespace()%}
            {%set ns.area_id='entrance'%}
            {%set ns.switch='switch.adaptive_lighting_'~ns.area_id%}
            {%set ns.lights=state_attr(ns.switch, "configuration").lights%}
            {{state_attr(ns.lights|first, 'color_temp')}}
          set_temperature:
            - service: script.adaptive_lighting_control
              data:
                action: 'set_color_temp'
                color_temp: '{{color_temp}}'
                adaptive_lighting_switch_entity_id: 'switch.adaptive_lighting_entrance'
          supports_transition_template: false
    ```
1. Add the following to your `configuration.yaml`
    ```
    light templates: !include configuration.d/light_templates.yaml
    ```
    (The `templates` is arbitrary, you can also put `lemon` there if you want.)
1. Put the following in a file called `adaptive_lighting_control.yaml` in a folder called `scripts.d`.
```
adaptive_lighting_control:
  alias: 'adaptive_lighting_control'
  description: |-
    Control lights of an adaptive lighting entity.
  variables:
    ##
    zigbee2mqtt_base_topic: |-
      {%if zigbee2mqtt_base_topic is defined%}
        {{zigbee2mqtt_base_topic}}
      {%else%}
        zigbee2mqtt
      {%endif%}
    adapt_brightness_switch_entity_id: |-
      {{adaptive_lighting_switch_entity_id |
        replace("adaptive_lighting",
                "adaptive_lighting_adapt_brightness")}}
    adapt_color_switch_entity_id: |-
      {{adaptive_lighting_switch_entity_id |
        replace("adaptive_lighting",
                "adaptive_lighting_adapt_color")}}
    is_brightness_being_adapted: '{{is_state(adapt_brightness_switch_entity_id, "on")}}'
    is_color_being_adapted: '{{is_state(adapt_color_switch_entity_id, "on")}}'
    mqtt_light_entities: |-
      {{integration_entities("mqtt") |
        select("match", "^light\.") |
        expand |
        map(attribute='entity_id') |
        list}}
  sequence:
  ## check if we can retrieve the lights controlled by the adaptive lighting switch
  - if:
    - condition: template
      value_template: '{{state_attr(adaptive_lighting_switch_entity_id, "configuration") | length == 0}}'
    then:
    ## allow us to retrieve the lights controlled by the adaptive lighting switch
    - service: adaptive_lighting.change_switch_settings
      data:
        entity_id: '{{adaptive_lighting_switch_entity_id}}'
        include_config_in_attributes: true
  - variables:
      adaptive_lighting_switch_lights: |-
        {{state_attr(adaptive_lighting_switch_entity_id, "configuration").lights}}
  - choose:
    - conditions:
      - condition: template
        value_template: '{{action == "on" or action == "prime"}}'
      sequence:
      ## only prime color_temperature if color is being adapted by adaptive lighting
      - if:
        - condition: template
          value_template: '{{is_color_being_adapted}}'
        then:
        ## iterate only lights that are currently off
        - repeat:
            for_each: |-
              {%set ns=namespace(list=[])%}
              {%for _ in adaptive_lighting_switch_lights |
                         expand |
                         selectattr("attributes.supported_color_modes", "defined") |
                         selectattr("attributes.supported_color_modes", "contains", "color_temp") |
                         selectattr("state", "==", "off") |
                         map(attribute="entity_id") |
                         list%}
                {%if _ in mqtt_light_entities%}
                  {%set ns.list=ns.list + [_]%}
                {%endif%}
              {%-endfor%}
              {{ns.list}}
            sequence:
            ## set the color temperature
            - service: mqtt.publish
              data_template:
                topic: '{{zigbee2mqtt_base_topic}}/{{state_attr(repeat.item, "friendly_name")}}/set'
                payload: |-
                  {
                    "color_temp": {{state_attr(adaptive_lighting_switch_entity_id, "color_temp_mired")}},
                    "transition": 0
                  }
      - if:
        - condition: template
          value_template: '{{action == "on"}}'
        then:
        ## turn on the lights using adaptive control
        - service: adaptive_lighting.apply
          data:
            entity_id:        '{{adaptive_lighting_switch_entity_id}}'
            adapt_brightness: '{{is_brightness_being_adapted}}'
            adapt_color:      '{{is_color_being_adapted}}'
            turn_on_lights:   true
        ## turn on only adaptive lighting in case user switched off brightness and/or color adapting
        - service: switch.turn_on
          target:
            entity_id:
            - '{{adaptive_lighting_switch_entity_id}}'
            # - '{{adapt_brightness_switch_entity_id}}'
            # - '{{adapt_color_switch_entity_id}}'
    - conditions:
      - condition: template
        value_template: '{{action == "off" or action == "enable_priming"}}'
      sequence:
      - if:
        - condition: template
          value_template: '{{action == "off"}}'
        then:
        ## turn lights off
        - service: light.turn_off
          target:
            entity_id: '{{state_attr(adaptive_lighting_switch_entity_id, "configuration").lights}}'
        ## always enable adaptive lighting to the maxx after turning lights off
        - service: switch.turn_on
          target:
            entity_id:
            - '{{adaptive_lighting_switch_entity_id}}'
            - '{{adapt_brightness_switch_entity_id}}'
            - '{{adapt_color_switch_entity_id}}'
      ## always enable priming of color temperature after the lights have been turned off
      - repeat:
          ## iterate all lights that can change color temperature
          for_each: |-
            {%set ns=namespace(list=[])%}
            {%for _ in adaptive_lighting_switch_lights |
                       expand |
                       selectattr("attributes.supported_color_modes", "defined") |
                       selectattr("attributes.supported_color_modes", "contains", "color_temp") |
                       map(attribute="entity_id") |
                       list%}
              {%if _ in mqtt_light_entities%}
                {%set ns.list=ns.list + [_]%}
              {%endif%}
            {%-endfor%}
            {{ns.list}}
          sequence:
          ## enable setting color temperature while lights are off
          - service: mqtt.publish
            data_template:
              topic: '{{zigbee2mqtt_base_topic}}/{{state_attr(repeat.item, "friendly_name")}}/set'
              payload: |-
                {
                  "color_options": {
                    "execute_if_off": true
                  }
                }
    - conditions:
      - condition: template
        value_template: '{{action == "set_level"}}'
      sequence:
      - action: switch.turn_off
        data:
          entity_id: '{{adapt_brightness_switch_entity_id}}'
      - action: light.turn_on
        data:
          brightness: '{{brightness}}'
        target:
          entity_id: '{{adaptive_lighting_switch_lights}}'
    - conditions:
      - condition: template
        value_template: '{{action == "set_color_temp"}}'
      sequence:
      - action: switch.turn_off
        data:
          entity_id: '{{adapt_color_switch_entity_id}}'
      - action: light.turn_on
        data:
          color_temp: '{{color_temp}}'
        target:
          entity_id: '{{adaptive_lighting_switch_lights}}'
    default: []
```
1. Add the following to your `configuration.yaml`
    ```
    script managed:         !include_dir_merge_named scripts.d/
    script ui:              !include scripts.yaml
    ```
    (The `managed` and `ui` are arbitrary, you can also put `apple` and/or `pear` there if you want - ha that even rhymes a little.)

Reload template entities, scripts from developer tools. Now you should be able to open an `adaptive_lighting_entrance` entity and control the light from the frontend. When turning the light off, the script will enable priming and turning the light on will prime the light before issuing a `light.turn_on`, etc.

This is waaaaaay too complex, so I'll just leave this here for someone to look at and think "that is waaaaaay too complex".

Warranty until the door for this one :-)
Grt,
